### ISSUE TITLE
Ticking entity Crash from Basilisk

### ISSUE THREAD

**Issue by Darkmega18** [linkisheroic/minestuckarsenal#1]
This was an issue I hit the other night on the server, I posted it to the minestuck main mod, but they said it's from yours, which kinda makes sense since it mentions something about grist drops and you add multipliers to them. The crash log is in the linked issue.

https://github.com/mraof/Minestuck/issues/171#event-1721464366

**Comment by linkisheroic** [comment]
I believe it's fixed in the next version. Added a null check to the handler.

**Comment by Darkmega18** [comment]
Alrighty, thanks.
